{
 "title": "AWS Elasticsearch",
 "tags": [
  "aws",
  "elasticsearch"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ClientId",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,ClientId)"
   },
   {
    "name": "DomainName",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,DomainName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Free storage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "ClusterStatus",
   "type": "vonage-status-panel",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "green",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "yellow",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "red",
     "crit": 1,
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "ClusterStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Green",
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Yellow",
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Red",
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "Searchable documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "EBS Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "WriteLatency",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "MasterCPUUtilization",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "EBS Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ReadLatency",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Cluster used space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterUsedSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterUsedSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "ClusterUsedSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ]
    },
    {
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Minimum" ]
    }
   ]
  }
 ]
}