{
 "title": "AWS S3",
 "description": "Visualize AWS S3 metrics",
 "tags": [
  "cloudwatch",
  "s3"
 ],
 "time": { "from": "now/M", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "dimension_values($region,AWS/S3,NumberOfObjects,BucketName)"
   },
   {
    "name": "filterid",
    "label": "FilterId",
    "query": "dimension_values($region,AWS/S3,AllRequests,FilterId)"
   }
  ]
 },
 "panels": [
  {
   "title": "List of Buckets",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "{{BucketName}}",
     "dimensions": { "BucketName": "$bucket", "StorageType": "StandardStorage" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "BucketSizeBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "StandardStorage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "BucketSizeBytes (History)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "StandardStorage" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NumberOfObjects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "StorageType": "AllStorageTypes" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Filtered Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "All_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "AllRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Get_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "GetRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Put_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PutRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Del_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeleteRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Head_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HeadRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Post_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PostRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "List_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ListRequests",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Filtered Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "FirstByteLatency_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FirstByteLatency",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "TotalReqLatency_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TotalRequestLatency",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Filtered Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Download_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Upload_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Filtered Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "4xx_err_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrors",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "5xx_err_{{BucketName}}",
     "application": { "filter": "" },
     "dimensions": { "BucketName": "$bucket", "FilterId": "$filterid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrors",
     "namespace": "AWS/S3",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}