{
 "title": "Blaster - RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{app=\"blaster\"}"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 }, "content": "# Blaster - PROD" },
  {
   "title": "Rate - Requests Per Second",
   "type": "graph",
   "description": "The number of requests per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"(app|tools).dfds.cloud/blaster\"}[5m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Errors - Failed Request Per Second",
   "type": "graph",
   "description": "The number of failed requests per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\",backend=~\"(app|tools).dfds.cloud/blaster\"}[5m]))",
     "legendFormat": "Failed Request Per Second"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Distributions of the amount of time each request takes in milliseconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"(app|tools).dfds.cloud/blaster\"}[5m]))/sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"(app|tools).dfds.cloud/blaster\"}[5m]))",
     "legendFormat": "Request duration"
    }
   ]
  }
 ]
}