{
 "title": "Grafana",
 "tags": [
  "Grafana",
  "Monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "grafanaversion",
    "query": "label_values(grafana_info,version)"
   },
   {
    "name": "grafanachart",
    "query": "label_values(grafana_info,chart)"
   },
   {
    "name": "grafanahost",
    "query": "label_values(kube_pod_info{pod=~\"grafana-.*\"},label_kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Grafana version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "content": "<center><h1>$grafanaversion<h1></center>"
  },
  {
   "title": "Chart Name",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 5 },
   "content": "<center><h1>$grafanachart<h1></center>"
  },
  {
   "title": "Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"grafana\"} * 1000"
    }
   ]
  },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"grafana\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"grafana-.*\"})"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"grafana-.*\"}) - sum(kube_pod_container_status_running{pod=~\"grafana-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"grafana-.*\"}) * 1000"
    }
   ]
  },
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "grafana_stat_active_users{}" }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "grafana_alerting_active_alerts" }
   ]
  },
  {
   "title": "Play Lists",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "grafana_stat_total_playlists" }
   ]
  },
  {
   "title": "Dashboards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "grafana_stat_totals_dashboard" }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"grafana-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$grafanahost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"grafana-.*\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"grafana-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$grafanahost\"})"
    }
   ]
  },
  {
   "title": "Pod CPU usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod_name=~\"grafana-.*\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$grafanahost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-server-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods cpu  usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"grafana-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$grafanahost\"})"
    }
   ]
  }
 ]
}