{
 "title": "Kubernetes Kube2Iam",
 "tags": [ "Kube2Iam" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Pods State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=\"kube2iam\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\",pod=~\"kube2iam-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=~\"fluentd-.*\"}"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"kube2iam-.*\"})"
    }
   ]
  },
  {
   "title": "Daemonset Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_daemonset_created{daemonset=\"kube2iam\"} * 1000"
    }
   ]
  },
  {
   "title": "Pod version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "content": "<center><h1>$podversion<h1></center>"
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pod memory usage on host",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"kube2iam-.*\", kubernetes_io_role=\"node\"}) / sum (machine_memory_bytes{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"kube2iam-.*\", kubernetes_io_role=\"node\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_role=\"node\"})"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pod CPU usage on host",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"kube2iam-.*\", kubernetes_io_role=\"node\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"kube2iam-.*\", kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=\"node\"})"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\", kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\", kubernetes_io_role=~\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network receive rate on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\", kubernetes_io_role=~\"node\"}[5m])) / sum(rate(node_network_receive_bytes_total{device!~\"lo\", kubernetes_io_role=~\"node\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Network transmit rate on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"kube2iam-.*\", kubernetes_io_role=~\"node\"}[5m])) / sum(rate(node_network_transmit_bytes_total{device!~\"lo\", kubernetes_io_role=~\"node\"}[5m])) * 100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"kube2iam-.*\"}) * 1000"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } }
 ]
}