{
 "title": "Kubernetes Weave Net",
 "tags": [ "Weave Net" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Pods state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"weave-net\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\",pod=~\"fluentd-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=~\"fluentd-.*\"}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"weave-net-.*\"})"
    }
   ]
  },
  {
   "title": "Daemonset Created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_created{daemonset=~\"weave-net\"} * 1000"
    }
   ]
  },
  {
   "title": "Pod version",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "content": "<center><h1>$podversion<h1></center>"
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Pod memory usage on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"master\"}) / sum (machine_memory_bytes{kubernetes_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"node\"}) / sum (machine_memory_bytes{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"node\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"weave-net-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_role=\"node\"})"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Pod CPU usage on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum (rate (container_cpu_usage_seconds_total{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"master\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"master\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod CPU usage on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": " sum (rate (container_cpu_usage_seconds_total{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"node\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"weave-net-.*\", kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"weave-net-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=\"node\"})"
    }
   ]
  }
 ]
}