{
 "title": "Kubernetes Pods",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Pod$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Pod$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod memory working bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$Pod$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$Pod$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$Pod$\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$Pod$\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}