{
 "title": "Kubernetes Cluster Health Overview",
 "tags": [
  "kubernetes",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane Components Down",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(up{job=\"kubernetes-apiservers\"}==1)"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h])> bool 5)"
    }
   ]
  },
  {
   "title": "Nodes Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Crashlooping Control Plane Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"kube-system\"}[1h]) > bool 5)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "PVCs > 90% Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(((kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)*100)>bool 90)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}!=bool 1)"
    }
   ]
  },
  {
   "title": "Control Plane Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Servers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / sum(up{job=\"kubernetes-apiservers\"})) * 100"
      }
     ]
    },
    {
     "title": "Controller Managers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
      }
     ]
    },
    {
     "title": "Schedulers UP",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(up{job=\"kube-scheduler\"} == 1) / sum(up{job=\"kube-scheduler\"})) * 100"
      }
     ]
    },
    {
     "title": "API Server Request Error Rate",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
      }
     ]
    },
    {
     "title": "API Server Request Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(verb) (rate(apiserver_request_latencies_sum[5m]) >= 0)",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "End to End Scheduling Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cluster:scheduler_e2e_scheduling_latency_seconds:quantile"
      }
     ]
    },
    {
     "title": "API Server Request Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_count{code!~\"2..\"}[5m]))",
       "legendFormat": "Error Rate"
      },
      {
       "expr": "sum(rate(apiserver_request_count[5m]))",
       "legendFormat": "Request Rate"
      }
     ]
    }
   ]
  }
 ]
}