{
 "title": "Kubernetes Deployment",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_labels, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{namespace=~\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\"^$deployment.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"^$deployment.*\"}[5m])) "
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\",deployment=~\"^$deployment$\"}) / sum(kube_deployment_status_replicas{namespace=~\"$namespace\",deployment=~\"^$deployment$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=~\"node\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\",deployment=~\"^$deployment$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",deployment=~\"^$deployment$\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{namespace=~\"$namespace\",deployment=~\"^$deployment.*\"})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{namespace=~\"$namespace\",deployment=~\"^$deployment.*\"})"
    }
   ]
  },
  { "title": "Detailed (Pod, Containers)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Deployment CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"^$deployment.*$\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"^$deployment.*$\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",name!~\"^k8s_.*\",pod_name=~\"^$deployment.*$\"}[5m])) by (pod_name, name, image)",
     "legendFormat": "docker: {{ pod_name }} | {{ image }} ({{ name }})"
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Deployment network I/O",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",namespace=~\"$namespace\",pod_name=~\"^$deployment.*$\"}[5m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}