{
 "title": "Kubernetes Nodes",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [
  "kubernetes",
  "nodes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "role", "label": "Node role", "query": "master,node" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-node-exporters\", kubernetes_io_role=~\"$role\"})-sum(up{job=\"kubernetes-node-exporters\", kubernetes_io_role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(1 - (avg by (instance) (irate(node_cpu_seconds_total{kubernetes_io_role=~\"$role\", mode=\"idle\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{kubernetes_io_role=~\"$role\"}) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes{kubernetes_io_role=~\"$role\"}+node_memory_Cached_bytes{kubernetes_io_role=~\"$role\"}) ) / sum(node_memory_MemTotal_bytes{kubernetes_io_role=~\"$role\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_io_role=~\"$role\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_io_role=~\"$role\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_io_role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{kubernetes_io_role=~\"$role\"}) /  count(node_cpu_seconds_total{mode=\"idle\",kubernetes_io_role=~\"$role\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{kubernetes_io_role=~\"$role\"}) /  count(node_cpu_seconds_total{mode=\"idle\",kubernetes_io_role=~\"$role\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (15m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load15{kubernetes_io_role=~\"$role\"}) /  count(node_cpu_seconds_total{mode=\"idle\",kubernetes_io_role=~\"$role\"}) * 100"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by(instance, cpu)(node_cpu_seconds_total{kubernetes_io_role=~\"$role\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_io_role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "All disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_io_role=~\"$role\", device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes{device!=\"tmpfs\",kubernetes_io_role=~\"$role\"}) * 100) / (sum(node_filesystem_size_bytes{device!=\"tmpfs\",kubernetes_io_role=~\"$role\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{kubernetes_io_role=~\"$role\"})"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Processes State",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "sum(node_procs_blocked{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "sum(node_procs_running{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\", kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest', kubernetes_io_role=~\"$role\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_io_role=~\"$role\"}) - sum(node_memory_MemFree_bytes{kubernetes_io_role=~\"$role\"}) - sum(node_memory_Cached_bytes{kubernetes_io_role=~\"$role\"}) + sum(node_memory_Buffers_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "RAM Cache "
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{kubernetes_io_role=~\"$role\"}) - sum(node_memory_SwapFree_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{kubernetes_io_role=~\"$role\"})",
     "legendFormat": "RAM Buffers"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{kubernetes_io_role=~\"$role\", device!=\"rootfs\"} - node_filesystem_free_bytes{kubernetes_io_role=~\"$role\", device!=\"rootfs\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{kubernetes_io_role=~\"$role\", device!=\"rootfs\"})",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk Read Data",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "KBs", "label": "Bytes read (-)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} - Bytes read"
    }
   ]
  },
  {
   "title": "Disk Write Data",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "KBs", "label": "Bytes write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} - Bytes written"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOs Current in Progress",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "iops", "label": "I/Os" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_now{kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{device!=\"rootfs\", kubernetes_io_role=~\"$role\"} [5m])) by (instance)",
     "legendFormat": "{{instance}} - Milliseconds spent doing I/Os"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\", kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\", kubernetes_io_role=~\"$role\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_drop_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "sum by (device) (irate(node_network_transmit_drop_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_errs_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "{{instance}} - Receive errors"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_errs_total{kubernetes_io_role=~\"$role\"}[5m]))",
     "legendFormat": "{{instance}} - Rransmit errors"
    }
   ]
  }
 ]
}