{
 "title": "Kubernetes Persistent Volumes",
 "tags": [
  "persistent volumes",
  "kubernetes"
 ],
 "time": { "from": "2018-05-31T07:38:17.639Z", "to": "2018-05-31T11:38:17.643Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubelet_volume_stats_capacity_bytes, namespace)"
   },
   {
    "name": "pvcname",
    "label": "PVC",
    "query": "label_values(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}, persistentvolumeclaim)"
   },
   { "name": "capacity", "label": "Capacity", "query": "50,60,70,80,90,95" }
  ]
 },
 "panels": [
  {
   "title": "PVCs > $capacity% Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(((kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)*100)>bool $capacity)"
    }
   ]
  },
  {
   "title": "List of PVCs > $capacity% used",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100)>$capacity"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}!=bool 1)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"elasticsearch\"}!=1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=\"$pvcname\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$namespace\",persistentvolumeclaim=\"$pvcname\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=\"$pvcname\"}*100"
    }
   ]
  }
 ]
}