{
 "title": "Kubernetes StatefulSet",
 "description": "-",
 "tags": [
  "kubernetes",
  "statefulsets"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation, namespace)"
   },
   {
    "name": "statefulset",
    "label": "StatefulSet",
    "query": "label_values(kube_statefulset_metadata_generation{namespace=~\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*$\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*$\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*\"}[5m])) "
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\",deployment=~\"^$statefulset.*\"}) / sum(kube_deployment_status_replicas{namespace=~\"$namespace\",deployment=~\"^$statefulset.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"^$statefulset.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=~\"node\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\",deployment=~\"^$statefulset.*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",deployment=~\"^$statefulset.*$\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{namespace=~\"$namespace\",deployment=~\"^$statefulset.*\"})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{namespace=~\"$namespace\",deployment=~\"^$statefulset.*\"})"
    }
   ]
  }
 ]
}