{
 "title": "Kubernetes FluentD Pods",
 "description": "Monitors the status of the FluentD daemonset setup that gathers logs from kubernetes and sends them to an endpoint",
 "tags": [ "FluentD" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "podversion",
    "query": "label_values(kube_pod_labels{pod=~\"fluentd-.*\"}, label_version)"
   }
  ]
 },
 "panels": [
  { "title": "Pods State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"fluentd-.*\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\",pod=~\"fluentd-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=~\"fluentd-.*\"}"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"fluentd-.*\"})"
    }
   ]
  },
  {
   "title": "Daemonset Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_daemonset_created{daemonset=~\"fluentd-.*\"} * 1000"
    }
   ]
  },
  {
   "title": "Pod version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "content": "<center><h1>$podversion<h1></center>"
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pod memory usage on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"master\"}) / sum (machine_memory_bytes{kubernetes_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"node\"}) / sum (machine_memory_bytes{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"node\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_role=\"node\"})"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pod CPU usage on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"master\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_role=\"master\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"master\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pod CPU usage on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"node\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_role=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"fluentd-.*\", kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_role=\"node\"})"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"master\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"master\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network transmit rate on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"master\"}[5m])) / sum(rate(node_network_transmit_bytes_total{device!~\"lo\", kubernetes_io_role=~\"master\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Network receive rate on master nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"master\"}[5m])) / sum(rate(node_network_receive_bytes_total{device!~\"lo\", kubernetes_io_role=~\"master\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Network receive rate on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"node\"}[5m])) / sum(rate(node_network_receive_bytes_total{device!~\"lo\", kubernetes_io_role=~\"node\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Network transmit rate on worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"fluentd-.*\", kubernetes_io_role=~\"node\"}[5m])) / sum(rate(node_network_transmit_bytes_total{device!~\"lo\", kubernetes_io_role=~\"node\"}[5m])) * 100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "kubernetes.namespace_name:\"kube-system\" AND kubernetes.pod_name:\"fluentd-*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"fluentd-.*?\"}) * 1000"
    }
   ]
  }
 ]
}