{
 "title": "Cluster Health Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Kubernetes Masters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Masters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{kubernetes_io_role=\"master\", job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Master Availability Zones",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(up{kubernetes_io_role=\"master\", job=\"kubernetes-nodes\"}) by (failure_domain_beta_kubernetes_io_zone))"
    }
   ]
  },
  {
   "title": "Masters Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_kubernetes_io_role=\"master\"}) / sum(up{kubernetes_io_role=\"master\", job=\"kubernetes-nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Master Memory Usage",
   "type": "singlestat",
   "description": "Shows memory usage of masters in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kops_k8s_io_instancegroup=~\"master.*\"}) / sum (machine_memory_bytes{kops_k8s_io_instancegroup=~\"master.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Master CPU Utilisation",
   "type": "singlestat",
   "description": "Shows CPU Utilisation on the masters",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kops_k8s_io_instancegroup=~\"master.*\"}[5m])) / sum (machine_cpu_cores{kops_k8s_io_instancegroup=~\"master.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Masters Disk Space Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kops_k8s_io_instancegroup=~\"master.*\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kops_k8s_io_instancegroup=~\"master.*\"}) * 100"
    }
   ]
  },
  { "title": "Kubernetes Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{kubernetes_io_role=\"node\", job=\"kubernetes-nodes\"})"
    }
   ]
  },
  {
   "title": "Node Availability Zones",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(up{kubernetes_io_role=\"node\", job=\"kubernetes-nodes\"}) by (failure_domain_beta_kubernetes_io_zone))"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_kubernetes_io_role=\"node\"}) / sum(up{kubernetes_io_role=\"node\", job=\"kubernetes-nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "singlestat",
   "description": "Shows memory usage of nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kops_k8s_io_instancegroup=\"nodes\"}) / sum (machine_memory_bytes{kops_k8s_io_instancegroup=\"nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Node CPU Utilisation",
   "type": "singlestat",
   "description": "Shows CPU Utilisation on the nodes",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kops_k8s_io_instancegroup=\"nodes\"}[5m])) / sum (machine_cpu_cores{kops_k8s_io_instancegroup=~\"nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes Disk Space Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kops_k8s_io_instancegroup=\"nodes\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kops_k8s_io_instancegroup=\"nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\",kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\",kubernetes_io_role=\"node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kubernetes Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Current Deployments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(min(kube_deployment_status_replicas_available) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Deployment Issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(kube_deployment_spec_replicas) without (instance, pod)) - count(min(kube_deployment_status_replicas_available) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Kubernetes Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"} == 1)"
    }
   ]
  },
  {
   "title": "Pod Issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase!=\"Running\"} == 1 and kube_pod_status_phase{phase!=\"Pending\"} == 1)"
    }
   ]
  },
  {
   "title": "Kubernetes API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "API Request Rate",
   "type": "singlestat",
   "description": "Rate of API requests per second",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{}[5m]))"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "singlestat",
   "description": "Rate of API Error (5xx) requests per second",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"^(?:5..)$\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "singlestat",
   "description": "Average Latency of the Kubernetes API",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 20 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(apiserver_request_latencies_bucket[5m]) > 0)"
    }
   ]
  }
 ]
}