{
 "title": "Kubernetes Monitoring Setup",
 "tags": [
  "Prometheus",
  "Monitoring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "promexporterdsversion",
    "query": "label_values(kube_daemonset_labels{daemonset=\"prometheus-node-exporter\"}, label_version)"
   },
   {
    "name": "promserverhost",
    "query": "label_values(kube_pod_info{pod=~\"prometheus-server-.*\"},label_kubernetes_io_hostname)"
   },
   {
    "name": "promalertmanagerhost",
    "query": "label_values(kube_pod_info{pod=~\"prometheus-alertmanager-.*\"},label_kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"prometheus-server\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"prometheus-server\"}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"prometheus-server\"}"
    }
   ]
  },
  {
   "title": "Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"prometheus-server\"} * 1000"
    }
   ]
  },
  { "title": "Deployment version", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 }, "content": "<center><h1>N/A<h1></center>" },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-server-.*\"})"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"prometheus-server-.*\"})"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-server-.*\"}) - sum(kube_pod_container_status_running{pod=~\"prometheus-server-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"prometheus-server-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"prometheus-server-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$promserverhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-server-.*\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-server-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$promserverhost\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod_name=~\"prometheus-server-.*\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$promserverhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-server-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods cpu  usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-server-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$promserverhost\"})"
    }
   ]
  },
  { "title": "Prometheus Alertmanager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"prometheus-alertmanager\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"prometheus-alertmanager\"}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"prometheus-alertmanager\"}"
    }
   ]
  },
  {
   "title": "Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 16 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"prometheus-alertmanager\"} * 1000"
    }
   ]
  },
  { "title": "Deployment version", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 9, "y": 16 }, "content": "<center><h1>N/A<h1></center>" },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-alertmanager-.*\"})"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"prometheus-alertmanager-.*\"})"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-alertmanager-.*\"}) - sum(kube_pod_container_status_running{pod=~\"prometheus-alertmanager-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"prometheus-alertmanager-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"prometheus-alertmanager-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$promalertmanagerhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-server-.*\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-alertmanager-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$promserverhost\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod_name=~\"prometheus-alertmanager-.*\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$promalertmanagerhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-alertmanager-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods cpu  usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-alertmanager-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$promalertmanagerhost\"})"
    }
   ]
  },
  { "title": "Prometheus Node Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Scheduled Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_desired_number_scheduled{daemonset=\"prometheus-node-exporter\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\",pod=~\"prometheus-node-exporter-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{daemonset=\"prometheus-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Daemonset Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 31 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_daemonset_created{daemonset=\"prometheus-node-exporter\"} * 1000"
    }
   ]
  },
  { "title": "Daemonset version", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 9, "y": 31 }, "content": "<center><h1>N/A<h1></center>" },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-node-exporter-.*\"})"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"prometheus-node-exporter-.*\"})"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-node-exporter-.*\"}) - sum(kube_pod_container_status_running{pod=~\"prometheus-node-exporter-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 31 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"prometheus-node-exporter-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Average Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-node-exporter-.*\"}) / count(container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-node-exporter-.*\"})) / (sum (machine_memory_bytes) / count(machine_memory_bytes))"
    }
   ]
  },
  {
   "title": "Use (on Average)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 33 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-node-exporter-.*\"})  / count(container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-node-exporter-.*\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-node-exporter-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes) / count(machine_memory_bytes)"
    }
   ]
  },
  {
   "title": "Average Pod CPU usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-node-exporter-.*\"}[5m]))) / (sum (machine_cpu_cores) / count(machine_cpu_cores))"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-node-exporter-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods cpu  usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-node-exporter-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores) / count(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "Prometheus KubeState Metrics Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"prometheus-kube-state-metrics\"}) "
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"prometheus-kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{deployment=\"prometheus-alertmanager\"}"
    }
   ]
  },
  {
   "title": "Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 46 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"prometheus-kube-state-metrics\"} * 1000"
    }
   ]
  },
  { "title": "Deployment version", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 9, "y": 46 }, "content": "<center><h1>N/A<h1></center>" },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-kube-state-metrics-.*\"})"
    }
   ]
  },
  {
   "title": "Total container restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"prometheus-kube-state-metrics-.*\"})"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"prometheus-kube-state-metrics-.*\"}) - sum(kube_pod_container_status_running{pod=~\"prometheus-kube-state-metrics-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 46 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"prometheus-kube-state-metrics-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 48 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"prometheus-kube-state-metrics-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$promserverhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 48 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"prometheus-kube-state-metrics-.*\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-kube-state-metrics-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 51 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$promserverhost\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{pod_name=~\"prometheus-kube-state-metrics-.*\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$promserverhost\"}) * 100"
    }
   ]
  },
  {
   "title": "Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"prometheus-kube-state-metrics-.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods cpu  usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"prometheus-kube-state-metrics-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {}
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$promserverhost\"})"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true
  }
 ]
}