{
 "title": "Services Overview",
 "tags": [
  "kubernetes",
  "red",
  "traefik"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(service)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_labels, namespace)"
   },
   {
    "name": "DomainName",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,DomainName)"
   },
   {
    "name": "ClientId",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,ClientId)"
   },
   {
    "name": "aws_services",
    "query": "dimension_values(us-east-1, AWS/Billing, EstimatedCharges, ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes cluster health overview",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "abs(min(up{job!=\"ec2-instances\",job!=\"kubernetes-service-endpoints\"})-1)",
     "legendFormat": "Jobs not running"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h])> bool 5)",
     "legendFormat": "Crash-looping pods"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})",
     "legendFormat": "Nodes not ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "Nodes disk pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "Nodes memory pressure"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Unschedulable nodes"
    },
    {
     "expr": "count(kube_node_spec_taint{key != \"node-role.kubernetes.io/master\"})"
    },
    {
     "expr": "abs(absent(count(kube_node_spec_taint{key != \"node-role.kubernetes.io/master\"}))-1)",
     "legendFormat": "Taints"
    },
    {
     "expr": "sum(((kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)*100)>bool 90)",
     "legendFormat": "PVC > 90% used"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}!=bool 1)",
     "legendFormat": "Unbound PVCs"
    }
   ]
  },
  {
   "title": "Services restarting",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1h]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ESClusterStatus",
   "type": "vonage-status-panel",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "green",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "yellow",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "red",
     "crit": 1,
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Cost per Service (rolling month)",
   "type": "graph",
   "description": "This shows the costs in graph format, by default over the current month",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "All services",
     "dimensions": { "Currency": "USD" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "{{ServiceName}}",
     "dimensions": { "Currency": "USD", "ServiceName": "$aws_services" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "Service name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "repeat": "service",
   "content": "<center><h1>$service</h1></center>"
  },
  { "title": "Rate (requests/sec)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 14 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service=~\"$service\"}[5m]))"
    }
   ]
  },
  { "title": "Errors (5xx errors/second)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 17 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{code=~\"5..\",service=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration (max duration last 5 minutes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "repeat": "service",
   "format": "dtdurations",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_request_duration_seconds_sum{service=~\"$service\"}[5m]))/sum(rate(traefik_request_duration_seconds_count{service=~\"$service\"}[5m]))"
    }
   ]
  }
 ]
}