{
 "title": "service overview dashboard",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(service)" },
   {
    "name": "DomainName",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,DomainName)"
   },
   {
    "name": "ClientId",
    "query": "dimension_values(eu-central-1,AWS/ES,FreeStorageSpace,ClientId)"
   },
   { "name": "aws_regions", "label": "Regions", "query": "regions()" },
   {
    "name": "aws_services",
    "label": "aws_services",
    "query": "dimension_values(us-east-1, AWS/Billing, EstimatedCharges, ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Kubernetes Cluster Health Overview",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "abs(min(up{job!=\"ec2-instances\",job!=\"kubernetes-service-endpoints\"})-1)",
     "legendFormat": "Jobs not running"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[1h])> bool 5)",
     "legendFormat": "Crashlooping pods"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})",
     "legendFormat": "Nodes not ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "Nodes disk pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "Nodes memory pressure"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "unschedulable nodes"
    },
    {
     "expr": "count(kube_node_spec_taint{key != \"node-role.kubernetes.io/master\"})"
    },
    {
     "expr": "abs(absent(count(kube_node_spec_taint{key != \"node-role.kubernetes.io/master\"}))-1)",
     "legendFormat": "Taints"
    },
    {
     "expr": "sum(((kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes)*100)>bool 90)",
     "legendFormat": "PVC > 90% used"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}!=bool 1)",
     "legendFormat": "Unbound PVCs"
    }
   ]
  },
  {
   "title": "ESClusterStatus",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "green",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "yellow",
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "red",
     "crit": 1,
     "decimals": 2,
     "dimensions": { "ClientId": "$ClientId", "DomainName": "$DomainName" },
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "default",
     "statistics": [ "Maximum" ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Month-to-Date Cost (All Accounts)",
   "type": "singlestat",
   "description": "This is the current estimated spend in the current month",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "Currency": "USD" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Month-to-Date Cost (This Account)",
   "type": "singlestat",
   "description": "This is the current estimated spend in the current month",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 3 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "Currency": "USD" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Cost Per Service",
   "type": "graph",
   "description": "This shows the costs in graph format, by default over the current month",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "All Services",
     "dimensions": { "Currency": "USD" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "{{ServiceName}}",
     "dimensions": { "Currency": "USD", "ServiceName": "$aws_services" },
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "region": "us-east-1",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "500 errors pr service",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(traefik_requests_total{code=~\"5..\",service=~\"$service\"}[5m])",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Services restarting",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1h]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}