{
 "title": "smartdata-aq",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Reponse times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Avg. response times [ms]" }
   ],
   "targets": [
    {
     "expr": "1000*sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\".*/smartdata/aq\"}[5m])) by (backend) / sum(rate(traefik_backend_request_duration_seconds_count{backend=~\".*/smartdata/aq\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Request count [1/s]" }
   ],
   "targets": [
    {
     "expr": "4*60*sum(rate(traefik_backend_requests_total{backend=~\".*/smartdata/aq\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "HTTP 2XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "4*60*sum(rate(traefik_backend_requests_total{backend=~\".*/smartdata/aq\",code=~\"2..\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "HTTP 3XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "4*60*sum(rate(traefik_backend_requests_total{backend=~\".*/smartdata/aq\",code=~\"3..\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "HTTP 4XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "4*60*sum(rate(traefik_backend_requests_total{backend=~\".*/smartdata/aq\",code=~\"4..\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "HTTP 5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "4*60*sum(rate(traefik_backend_requests_total{backend=~\".*/smartdata/aq\",code=~\"5..\"}[5m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}