{
 "title": "Traefik RED Metrics",
 "tags": [
  "traefik",
  "prometheus",
  "red",
  "ingress"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(traefik_requests_total{service!=\"/\",service!=\"traefik\",service!=\"httpn\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Rate - Requests Per Second",
   "type": "graph",
   "description": "The number of requests per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service=~\"$service\"}[5m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Errors - Failed Request Per Second",
   "type": "graph",
   "description": "The number of failed requests per second",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{code=~\"5..\",service=~\"$service\"}[5m]))",
     "legendFormat": "Failed Request Per Second"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Distributions of the amount of time each request takes in milliseconds",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_request_duration_seconds_sum{service=~\"$service\"}[5m]))/sum(rate(traefik_request_duration_seconds_count{service=~\"$service\"}[5m]))*1000",
     "legendFormat": "Request duration"
    }
   ]
  }
 ]
}