{
 "title": "Tracking Services",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 }, "content": "# TRACKING STREAM" },
  {
   "title": "Tracking Stream Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "memory " }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{container_name=~\"trackingstream-.*\"}) ",
     "legendFormat": "{{spec memory limit}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\"trackingstream-.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Tracking Stream CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name=~\"trackingstream.*\"}[5m]) * 1000) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_name=~\"trackingstream-.*\"}) / 100",
     "legendFormat": "{{max requested cores}}"
    },
    {
     "expr": "(sum(container_spec_cpu_quota{container_name=~\"trackingstream-.*\"}) / 1000) / (count(container_spec_cpu_shares{container_name=~\"trackingstream-.*\"}))",
     "legendFormat": "{{min requested cores}}"
    }
   ]
  },
  {
   "title": "Tracking Stream Total Core Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"trackingstream-.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Tracking Stream Memory Consumption",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"trackingstream-.*\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 13 }, "content": "# TRACKING STORE" },
  {
   "title": "Tracking Store Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "memory " }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{container_name=~\"trackingstore-.*\"}) ",
     "legendFormat": "{{spec memory limit}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\"trackingstore-.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Tracking Store CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name=~\"trackingstore.*\"}[5m]) * 1000) by (pod_name)"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_name=~\"trackingstore-.*\"}) / 100",
     "legendFormat": "{{max requested cores}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=~\"trackingstore-.*\"}) / 1000",
     "legendFormat": "{{min requested cores}}"
    }
   ]
  },
  {
   "title": "Tracking Store Total Core Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"trackingstore-.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Tracking Store Memory Consumption",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"trackingstore-.*\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 26 }, "content": "# KRONE INTEGRATOR" },
  {
   "title": "Krone Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "memory " }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{container_name=~\"krone-.*\"}) ",
     "legendFormat": "{{spec memory limit}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\"krone-.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Krone CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name=~\"krone.*\"}[5m]) * 1000) by (pod_name)"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_name=~\"krone-.*\"}) / 100",
     "legendFormat": "{{max requested cores}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=~\"krone-.*\"}) / 1000",
     "legendFormat": "{{min requested cores}}"
    }
   ]
  },
  {
   "title": "Krone integrator Core Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"krone-.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Krone integrator Memory Consumption",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 34 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"krone-.*\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 39 }, "content": "# TRUCKCOM INTEGRATOR" },
  {
   "title": "Truckcom Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes", "label": "memory " }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{container_name=~\"truckcomreceiver-.*\"}) ",
     "legendFormat": "{{spec memory limit}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\"truckcomreceiver-.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "TruckCom CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name=~\"truckcomreceiver-.*\"}[5m]) * 1000) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_name=~\"truckcomreceiver-.*\"}) / 100",
     "legendFormat": "{{max requested cores}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=~\"truckcomreceiver-.*\"}) / 1000",
     "legendFormat": "{{min requested cores}}"
    }
   ]
  },
  {
   "title": "TruckCom integrator Core Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"truckcomreceiver-.*\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "TruckCom integrator Memory Consumption",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 47 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"truckcomreceiver-.*\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 52 }, "content": "# VELOCITY STREAM INTEGRATOR" },
  {
   "title": "Velocity Stream integrator Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "memory " }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{container_name=~\"velocitystreamintegrator-.*\"}) ",
     "legendFormat": "{{spec memory limit}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\"velocitystreamintegrator-.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Velocity Stream integrator CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name=~\"velocitystreamintegrator-.*\"}[5m]) * 1000) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_name=~\"velocitystreamintegrator-.*\"}) / 100",
     "legendFormat": "{{max requested cores}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container_name=~\"velocitystreamintegrator-.*\"}) / 1000",
     "legendFormat": "{{min requested cores}}"
    }
   ]
  },
  {
   "title": "TruckCom integrator Memory Consumption",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 54 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"POD\", pod_name=~\"velocitystreamintegrator-.*\"})"
    }
   ]
  },
  {
   "title": "TruckCom integrator Core Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 59 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=~\"velocitystreamintegrator-.*\"}[5m]))\n"
    }
   ]
  }
 ]
}