{
 "title": "Traefik",
 "description": "Traefik dashboard Prometheus",
 "tags": [
  "traefik",
  "prometheus",
  "ingress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(backend)" },
   { "name": "percentiles", "label": "Percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"traefik\"}"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"kube-system\",condition=\"true\",pod=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"kube-system\",pod=~\"traefik.*\"}"
    }
   ]
  },
  {
   "title": "5xx Error Count last 5 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Chart Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_deployment_labels{deployment=\"traefik\"}",
     "legendFormat": "{{label_chart}}"
    }
   ]
  },
  {
   "title": "Environment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, node_boot_time_seconds{cluster_name=~\".+\"})",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Rate - Requests Per Second",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Rate - Requests Per Second",
   "type": "graph",
   "description": "The number of requests per second",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=~\"$service\"}[5m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Current active endpoints",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{backend!=\"httpn\",backend!=\"http\"}) by (backend)"
    }
   ]
  },
  {
   "title": "Errors - Failed Request Per Second",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\",backend=~\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors - Failed Request Per Second",
   "type": "graph",
   "description": "The number of failed requests per second",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\",backend=~\"$service\"}[5m]))",
     "legendFormat": "Failed Request Per Second"
    }
   ]
  },
  {
   "title": "Duration in ms - Max value",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"$service\"}[5m]))/sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"$service\"}[5m]))*1000"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Distributions of the amount of time each request takes in milliseconds",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_request_duration_seconds_sum{backend=~\"$service\"}[5m]))/sum(rate(traefik_backend_request_duration_seconds_count{backend=~\"$service\"}[5m]))*1000",
     "legendFormat": "Request duration"
    }
   ]
  },
  {
   "title": "Error count per service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "5xx and 4xx pr service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) by (backend)* 1000",
       "legendFormat": "{{backend}} 5xx"
      },
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=~\"4..\"}[5m])) by (backend)* 1000",
       "legendFormat": "{{backend}} 4xx"
      }
     ]
    }
   ]
  },
  {
   "title": "Traefik Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{container_name=\"traefik\"}[5m]))",
       "legendFormat": "Max CPU Used"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"traefik\"})",
       "legendFormat": "Requested CPU"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"traefik\"})",
       "legendFormat": "Limit CPU"
      },
      {}
     ]
    },
    {
     "title": "Traefik max memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_usage_bytes{container_name=\"traefik\"})",
       "legendFormat": "Max memory used"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\"traefik\"})",
       "legendFormat": "Requested memory usage"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\"traefik\"})",
       "legendFormat": "Limit memory usage"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total{backend=\"http\"})",
       "legendFormat": "{{http}}"
      },
      {
       "expr": "sum(traefik_backend_requests_total{backend=\"https\"})",
       "legendFormat": "{{https}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average response time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_request_duration_seconds_sum) by (backend) / sum(traefik_backend_request_duration_seconds_count) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Latency [[percentiles]]th Percentile / 5 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_backend_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "Global Latency"
      }
     ]
    },
    {
     "title": "Node Latency [[percentiles]]th Percentile / 5 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.$percentiles, (sum(rate(traefik_backend_request_duration_seconds_bucket[5m])) by (instance, le)) * on() group_left(node) (kube_pod_labels{label_app=\"traefik\"} * on(pod) group_left(node) kube_pod_info))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apdex Score (over 5 min)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(traefik_backend_request_duration_seconds_bucket{code!~\"5..\",le=\"0.3\"}[5m])) + sum(rate(traefik_backend_request_duration_seconds_bucket{code!~\"5..\",le=\"1.2\"}[5m])))/2/sum(rate(traefik_backend_request_duration_seconds_count[5m]))",
       "legendFormat": "Score"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP status codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status code 200 over 5min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=~\"2..\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Others status code over 5min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code!~\"2..|5..\"}[5m])) by (method, code)",
       "legendFormat": "{{ method }} : {{code}}"
      }
     ]
    },
    {
     "title": "Total Status Code Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Status code 5xx over 5min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=~\"5..\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Successful Status Code Count (5min)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=~\"2..\"}[5m])) by (backend,method)",
       "legendFormat": "{{backend}} {{method}}"
      }
     ]
    },
    {
     "title": "Bad Status Code Count (5m)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code!~\"2..\"}[5m])) by (backend,method,code)",
       "legendFormat": "{{backend}} {{method}} {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_backend_requests_total) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Total requests per service over 5 min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total[5m])) by (backend)",
       "legendFormat": "{{backend}}"
      }
     ]
    }
   ]
  }
 ]
}