{
 "title": "Wikijs",
 "tags": [ "Wikijs" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "wikijsdeploymenthost",
    "query": "label_values(kube_pod_info{pod=~\"wikijsdeployment-.*\"},node)"
   },
   {
    "name": "mongodbdeploymenthost",
    "query": "label_values(kube_pod_info{pod=~\"mongodbdeployment-.*\", namespace=\"wikijs\"},node)"
   },
   {
    "name": "wikiversion",
    "query": "label_values(kube_deployment_labels{deployment=\"wikijsdeployment\"}, label_version)"
   }
  ]
 },
 "panels": [
  { "title": "Deployment Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total deployments",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_labels{namespace=\"wikijs\"})"
    }
   ]
  },
  {
   "title": "Wiki Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"wikijsdeployment\"} * 1000"
    }
   ]
  },
  {
   "title": "MongoDB Deployment Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_created{deployment=\"mongodbdeployment\"} * 1000"
    }
   ]
  },
  { "title": "Wikijs Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"wikijsdeployment\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"wikijsdeployment-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$wikijsdeploymenthost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"wikijsdeployment-.*\", kubernetes_io_hostname=~\"$wikijsdeploymenthost\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"wikijsdeployment-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"wikijsdeployment-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"wikijsdeployment\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$wikijsdeploymenthost\"})"
    }
   ]
  },
  {
   "title": "Deployment version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "content": "<center><h1>$wikiversion<h1></center>"
  },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"wikijsdeployment-.*\"})"
    }
   ]
  },
  {
   "title": "Pod CPU usage on host",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"wikijsdeployment-.*\", kubernetes_io_hostname=\"$wikijsdeploymenthost\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$wikijsdeploymenthost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=\"$mongodbdeploymenthost\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"wikijsdeployment-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"wikijsdeployment-.*\"}) - sum(kube_pod_container_status_running{pod=~\"wikijsdeployment-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$mongodbdeploymenthost\"})"
    }
   ]
  },
  { "title": "Wikijs MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Scheduled Replicas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=\"mongodbdeployment\", namespace=\"wikijs\"})"
    }
   ]
  },
  {
   "title": "Pod memory usage (on host)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((container_memory_working_set_bytes{pod_name=~\"mongodbdeployment-.*\", name!~\"POD\"})) / sum (machine_memory_bytes{kubernetes_io_hostname=\"$mongodbdeploymenthost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 17 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=~\"$mongodbdeploymenthost\"})"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"mongodbdeployment-.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Basic Pod Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 17 },
   "targets": [
    {
     "expr": " (kube_pod_labels)* on(pod) group_left(version) (kube_pod_start_time{pod=~\"mongodbdeployment-.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"wikijsdeployment\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=\"$mongodbdeploymenthost\"})"
    }
   ]
  },
  { "title": "Deployment version", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 }, "content": "<center><h1>N/A<h1></center>" },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"wikijsdeployment-.*\"})"
    }
   ]
  },
  {
   "title": "Pod CPU usage on host",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=\"$mongodbdeploymenthost\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=\"$mongodbdeploymenthost\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=\"$mongodbdeploymenthost\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"mongodbdeployment-.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{pod=~\"wikijsdeployment-.*\"}) - sum(kube_pod_container_status_running{pod=~\"wikijsdeployment-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=\"$mongodbdeploymenthost\"})"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Network Receive",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"wikijsdeployment-.*\", kubernetes_io_hostname=~\"$wikijsdeploymenthost\", namespace=\"wikijs\"}[5m])) + sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=\"$mongodbdeploymenthost\", namespace=\"wikijs\"}[5m]))"
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"wikijsdeployment-.*\", namespace=\"wikijs\"}[5m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"mongodbdeployment-.*\", namespace=\"wikijs\"}[5m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"wikijsdeployment-.*\", kubernetes_io_hostname=~\"$wikijsdeploymenthost\", namespace=\"wikijs\"}[5m])) + sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"mongodbdeployment-.*\", kubernetes_io_hostname=\"$mongodbdeploymenthost\", namespace=\"wikijs\"}[5m]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
 ]
}